import Head from "next/head";
import { useState } from "react";
import Link from 'next/link'

function MobileUrl(props) {
    return (
        <Link className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" href={`https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.${props.url}%2F&utm_source=search_console&tab=mobile&hl=de`} target="_blank" rel="noreferrer">
            <a className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" target="_blank" rel="noreferrer">Mobile Check</a>
        </Link>
    )
}
function DesktopUrl(props) {
    return (
        <Link className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" href={`https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.${props.url}%2F&utm_source=search_console&tab=desktop&hl=de`} target="_blank" rel="noreferrer">
            <a className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" target="_blank" rel="noreferrer">Desktop Check</a>
        </Link>
    )
}
function DMARCCheck(props) {
    return (
        <Link className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" href={`https://dmarcian.com/dmarc-inspector/?domain=${props.url}`} target="_blank" rel="noreferrer">
            <a className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" target="_blank" rel="noreferrer">DMARC Check</a>
        </Link>
    )
}
function SPFCheck(props) {
    return (
        <Link href={`https://dmarcian.com/spf-survey/?domain=${props.url}`}>
            <a className="font-bold text-sm block p-4 bg-werk rounded-md text-white flex items-center" target="_blank" rel="noreferrer">SPF Check</a>
        </Link>
    )
}

export default function Intro() {
    const [value, setValue] = useState('');
    const handleChange = (e) => setValue(e.target.value);

    return(
        <div className="flex flex-col w-full items-center justify-center">
            <Head>
                <title>Create Werkkasten Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="my-12 px-4 ">
                <svg data-name="Ebene 1" xmlns="http://www.w3.org/2000/svg" className="App-logo w-64 fill-werk"
                     viewBox="0 0 499.17 500.6">
                    <path
                        d="M466.46 395.85a42.37 42.37 0 0 0 27.14-52.51l-87.28-274h.07L392.14 24.6a35.36 35.36 0 0 0-44.36-22.93l-44.72 14.24v.07l-274 87.28A40.92 40.92 0 0 0 4.86 124a40.93 40.93 0 0 0-2.9 31.77l87.28 274h-.07l14.25 44.73a35.36 35.36 0 0 0 44.36 22.92l44.73-14.25v-.06ZM92.5 169.3l235.52-75 75 235.52-235.52 75Z"/>
                    <rect x="416.41" y="417.84" width="82.76" height="82.76" rx="13.85"/>
                </svg>
            </div>

            <div className="text-2xl lg:text-4xl text-gray-800 text-center w-full lg:w-6/12 mb-8 px-4">
                Wir sind eine digitale Werbeagentur und lieben es Webseiten aus stürmischen Zustände wieder in sicheren Hafen anzudocken. Sie haben Fragen? Wir freuen uns auf Sie.
            </div>
            <div className="mb-8 text-gray-800 text-lg lg:text-2xl text-center w-full lg:w-6/12 mb-12 px-4">
                Egal, mit welcher CMS oder Shop-System Sie Ihre Webseite betreiben, <span className="text-werk">werkkasten</span> hat eine Lösung für Sie.
            </div>
            <div className="flex flex-wrap items-center justify-center mb-12">
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">Magento</div>
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">Shopware</div>
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">Pimcore</div>
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">ExpressionEngine</div>
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">Laravel</div>
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">WordPress</div>
                <div className="px-6 py-3 bg-gray-100 rounded-full text-gray-600 mb-3 mr-3">WooCommerce</div>
            </div>
            <div className="pointer-events-auto mb-12 px-4">
                <Link className="font-bold block border border-2 border-werk text-werk px-6 py-4 rounded-full hover:bg-werk hover:text-white hover:shadow-2xl" href="/about">Entdecken Sie Werkkasten</Link>
            </div>

            <div className="flex flex-wrap flex-col lg:flex-row">
                <div className="w-full lg:w-1/2 xl:w-1/3 px-8 mb-8">
                    <div className="relative w-full bg-blue-100 bg-opacity-25 p-8 rounded-xl shadow">

                        <div className="flex items-center">
                            <div className="text-4xl">Homepage Check</div>
                        </div>
                        <div className="mt-8">
                            <div className="text-xl mb-8">Prüfen Sie ob Ihre Homepage gut optimiert ist. Tragen Sie Ihre Domainnamen und Domain-Endung in das Eingabefeld ein und wählen Sie Ihren Check-Button.</div>
                            <div className="w-full flex flex-col lg:flex-row items-center">
                                <div className="w-full mb-4 lg:mr-4">
                                    <input className="block w-full border-2 border-werk p-3 mr-4 rounded-md" type="text" value={value} onChange={handleChange} placeholder="ihredomainname.tld*" />
                                </div>
                                <div className="w-full mb-4 lg:mr-4">
                                    <MobileUrl url={value} />
                                </div>
                                <div className="w-full mb-4">
                                    <DesktopUrl url={value} />
                                </div>
                            </div>
                            <div><span className="text-sm">* tld: Domain-Endung wie zB. de, com, org usw.</span></div>
                        </div>
                    </div>
                </div>

                <div className="w-full lg:w-1/2 xl:w-1/3 px-8 mb-8">
                    <div className="relative w-full bg-blue-300 bg-opacity-25 p-8 rounded-xl shadow">

                        <div className="flex items-center">
                            <div className="text-4xl">DMARC Check</div>
                        </div>


                        <div className="mt-8">
                            <div className="text-xl mb-8">Verfügt Ihre Domain über einen gültigen DMARC-Eintrag? Verhindert Ihre DMARC-Richtlinie den Missbrauch Ihrer Domain durch Phisher und Spammer?</div>
                            <div className="w-full flex flex-col lg:flex-row items-center">
                                <div className="w-full mb-4 lg:mr-4">
                                    <input className="block w-full border-2 border-werk p-3 mr-4 rounded-md" type="text" value={value} onChange={handleChange} placeholder="ihredomainname.tld*" />
                                </div>
                                <div className="w-full mb-4 lg:mr-4">
                                    <DMARCCheck url={value} />
                                </div>
                            </div>
                            <div><span className="text-sm">* tld: Domain-Endung wie zB. de, com, org usw.</span></div>
                        </div>


                    </div>
                </div>

                <div className="w-full lg:w-1/2 xl:w-1/3 px-8 mb-8">
                    <div className="relative w-full bg-blue-100 bg-opacity-25 p-8 rounded-xl shadow">

                        <div className="flex flex-col">
                            <div className="text-4xl mb-4">SPF Check</div>
                            <p className="text-sm">
                                <span className="font-bold">Was ist SPF?</span> Sender Policy Framework (SPF) wird verwendet, um den Absender einer E-Mail zu authentifizieren.
                            </p>
                        </div>


                        <div className="mt-8">
                            <div className="text-xl mb-8">Verfügt Ihre Domain über einen gültigen SPF-Eintrag und ist diese ausreichend?</div>
                            <div className="w-full flex flex-col lg:flex-row items-center">
                                <div className="w-full mb-4 lg:mr-4">
                                    <input className="block w-full border-2 border-werk p-3 mr-4 rounded-md" type="text" value={value} onChange={handleChange} placeholder="ihredomainname.tld*" />
                                </div>
                                <div className="w-full mb-4 lg:mr-4">
                                    <SPFCheck url={value} />
                                </div>
                            </div>
                            <div><span className="text-sm">* tld: Domain-Endung wie zB. de, com, org usw.</span></div>
                        </div>


                    </div>
                </div>
            </div>

        </div>
    )
}